[package]
name = "shieldify"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/JohnScience/shieldify"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.72"
toml = "0.7.6"
markdown = "1.0.0-alpha.11"
